[package]
name = "bahlily-shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
audio-core = { path = "audio-core" }
tauri = { version = "2", features = [] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bin]]
name = "bahlily-shell"
path = "src/main.rs"
