# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_core/v1/audio.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "audio_core/v1/audio.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x61udio_core/v1/audio.proto\x12\raudio_core.v1"\x9a\x01\n\x0c\x41udioSegment\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x12\n\nsegment_id\x18\x04 \x01(\x04\x12.\n\x0b\x64\x65vice_type\x18\x05 \x01(\x0e\x32\x19.audio_core.v1.DeviceType\x12\x10\n\x08trace_id\x18\x06 \x01(\t"\x14\n\x12StreamAudioRequest"C\n\x13StreamAudioResponse\x12,\n\x07segment\x18\x01 \x01(\x0b\x32\x1b.audio_core.v1.AudioSegment*]\n\nDeviceType\x12\x1b\n\x17\x44\x45VICE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x44\x45VICE_TYPE_MICROPHONE\x10\x01\x12\x16\n\x12\x44\x45VICE_TYPE_SYSTEM\x10\x02\x32\x66\n\x0c\x41udioService\x12V\n\x0bStreamAudio\x12!.audio_core.v1.StreamAudioRequest\x1a".audio_core.v1.StreamAudioResponse0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "audio_core.v1.audio_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DEVICETYPE"]._serialized_start = 292
    _globals["_DEVICETYPE"]._serialized_end = 385
    _globals["_AUDIOSEGMENT"]._serialized_start = 45
    _globals["_AUDIOSEGMENT"]._serialized_end = 199
    _globals["_STREAMAUDIOREQUEST"]._serialized_start = 201
    _globals["_STREAMAUDIOREQUEST"]._serialized_end = 221
    _globals["_STREAMAUDIORESPONSE"]._serialized_start = 223
    _globals["_STREAMAUDIORESPONSE"]._serialized_end = 290
    _globals["_AUDIOSERVICE"]._serialized_start = 387
    _globals["_AUDIOSERVICE"]._serialized_end = 489
# @@protoc_insertion_point(module_scope)
