[package]
name = "audio-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "audio_core"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
prost = "0.13"
thiserror = "1"
hound = "3.5"
tokio-stream = "0.1"
silero_rs = { git = "https://github.com/emotechlab/silero-rs", package = "silero" }

[target.'cfg(target_os = "macos")'.dependencies]
cpal = "=0.15.3"
cidre = { git = "https://github.com/yury/cidre", default-features = false, features = [
  "av",
  "sc",
  "cat",
  "blocks",
  "async",
  "macos_13_0",
] }

[build-dependencies]
tonic-build = "0.12"
protoc-bin-vendored = "3"
