# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcription/v1/transcription.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'transcription/v1/transcription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$transcription/v1/transcription.proto\x12\x10transcription.v1\"\xad\x02\n\x11TranscriptSegment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nsegment_id\x18\x02 \x01(\x04\x12\x17\n\nconfidence\x18\x03 \x01(\x02H\x00\x88\x01\x01\x12\x12\n\nis_partial\x18\x04 \x01(\x08\x12(\n\x06\x65ngine\x18\x05 \x01(\x0e\x32\x18.transcription.v1.Engine\x12\x12\n\nmodel_name\x18\x06 \x01(\t\x12\x18\n\x10\x61udio_start_time\x18\x07 \x01(\x01\x12\x16\n\x0e\x61udio_end_time\x18\x08 \x01(\x01\x12\x15\n\x08language\x18\t \x01(\tH\x01\x88\x01\x01\x12\x14\n\x0crecording_id\x18\n \x01(\t\x12\x10\n\x08trace_id\x18\x0b \x01(\tB\r\n\x0b_confidenceB\x0b\n\t_language\"\x1a\n\x18StreamTranscriptsRequest\"Q\n\x19StreamTranscriptsResponse\x12\x34\n\x07segment\x18\x01 \x01(\x0b\x32#.transcription.v1.TranscriptSegment*I\n\x06\x45ngine\x12\x16\n\x12\x45NGINE_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x45NGINE_WHISPER\x10\x01\x12\x13\n\x0f\x45NGINE_PARAKEET\x10\x02\x32\x86\x01\n\x14TranscriptionService\x12n\n\x11StreamTranscripts\x12*.transcription.v1.StreamTranscriptsRequest\x1a+.transcription.v1.StreamTranscriptsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription.v1.transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENGINE']._serialized_start=473
  _globals['_ENGINE']._serialized_end=546
  _globals['_TRANSCRIPTSEGMENT']._serialized_start=59
  _globals['_TRANSCRIPTSEGMENT']._serialized_end=360
  _globals['_STREAMTRANSCRIPTSREQUEST']._serialized_start=362
  _globals['_STREAMTRANSCRIPTSREQUEST']._serialized_end=388
  _globals['_STREAMTRANSCRIPTSRESPONSE']._serialized_start=390
  _globals['_STREAMTRANSCRIPTSRESPONSE']._serialized_end=471
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=549
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
